apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v91w3uwaw-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v91w3uwaw-java-quarkus-gitops